
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog
import checker

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_excel():
    os.system("PAPERS.xlsx")


def open_folder():
    filename = filedialog.askdirectory()
    entry_answer_sheet.insert(0, filename)


def open_file():
    name = filedialog.askopenfilename()
    entry_answer_key.insert(0, name)


window = Tk()

window.geometry("600x600")
window.configure(bg = "#FFFFFF")
window.title("Test Paper Checker")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    166.0,
    306.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    465.0,
    364.0,
    image=image_image_2
)

button_img_evaluate = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_evaluate = Button(
    image=button_img_evaluate,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: checker.checking(entry_answer_key.get(), entry_answer_sheet.get()),
    relief="flat"
)
button_evaluate.place(
    x=111.0,
    y=370.0,
    width=122.0,
    height=55.0
)

button_img_open = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_open_file = Button(
    image=button_img_open,
    borderwidth=0,
    highlightthickness=0,
    command=open_excel,
    relief="flat"
)
button_open_file.place(
    x=111.0,
    y=443.0,
    width=122.0,
    height=55.0
)

entry_img_anspath = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_anspath = canvas.create_image(
    172.0,
    323.0,
    image=entry_img_anspath
)
entry_answer_sheet = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_answer_sheet.place(
    x=52.0,
    y=303.0,
    width=240.0,
    height=38.0
)

button_img_folder = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_sheet_folder = Button(
    image=button_img_folder,
    borderwidth=0,
    highlightthickness=0,
    command=open_folder,
    relief="flat"
)
button_sheet_folder.place(
    x=268.0,
    y=312.0,
    width=24.0,
    height=22.0
)

entry_img_keypath = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_keypath = canvas.create_image(
    166.0,
    225.0,
    image=entry_img_keypath
)
entry_answer_key= Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_answer_key.place(
    x=46.0,
    y=205.0,
    width=240.0,
    height=38.0
)

button_img_addimg = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_answer_key = Button(
    image=button_img_addimg,
    borderwidth=0,
    highlightthickness=0,
    command=open_file,
    relief="flat"
)
button_answer_key.place(
    x=260.0,
    y=210.0,
    width=30.0,
    height=30.0
)
window.resizable(False, False)
window.mainloop()
